name: Dev Container Build and Push Image

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"
    pull_requests:
      branches:
        - "main"
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      id: checkout
      uses: actions/checkout@v1
    -
          
